name: Deploy To EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./goodsending/src/main/resources/application.yml

      - name: gradlew에 실행 권한 추가
        run: chmod +x ./goodsending/gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build
        working-directory: ./goodsending

      - name: 빌드된 파일 이름 변경하기
        run: mv ./goodsending/build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/goodsending-server/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/goodsending-server/current
            mkdir /home/ubuntu/goodsending-server/current
            mv /home/ubuntu/goodsending-server/tobe/project.jar /home/ubuntu/goodsending-server/current/project.jar
            cd /home/ubuntu/goodsending-server/current
            sudo fuser -k -n tcp 8080 || true 
            nohup java -jar project.jar > ./output.log 2>&1 & 
            rm -rf /home/ubuntu/goodsending-server/tobe